//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamperSignInSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamperInfoTable
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Self_Sign { get; set; }
        public string Approved_Pick_Up { get; set; }
        public string Sign_In_Signature { get; set; }
        public string Time_In { get; set; }
        public string Sign_Out_SIgnature { get; set; }
        public string Time_Out { get; set; }
    }
}
